In [1]:
import polars as pl
filepath = "../../data/ActionTreatmentMetaDataExport.csv"
df = pl.read_csv(filepath, null_values=["NA"])
df.head()

shape: (5, 99)
┌─────┬────────────┬────────────┬───────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│     ┆ IsSMSEnabl ┆ pySubjectT ┆ ProductNa ┆ ... ┆ IsPaidEnab ┆ ImageAltTe ┆ ImageURL_W ┆ ImageTarge │
│ --- ┆ ed         ┆ ype        ┆ me        ┆     ┆ led        ┆ xt_Web     ┆ eb         ┆ tURL_Web   │
│ i64 ┆ ---        ┆ ---        ┆ ---       ┆     ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆ f64        ┆ str        ┆ str       ┆     ┆ str        ┆ str        ┆ str        ┆ str        │
╞═════╪════════════╪════════════╪═══════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 0   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 1   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 2   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 3   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 4   ┆ 0.0        ┆ Data-Decis ┆ Tuin      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
└─────┴────────────┴────────────┴───────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [10]:
df.select(pl.col('^py.*$')).columns

['pySubjectType',
 'pyIsPropositionActive',
 'pyDeliverOffline',
 'pySpecifyEmailSubject',
 'pyChannel',
 'pySubjectID',
 'pyTreatment',
 'pyPreviousComponent',
 'pyGroup',
 'pyApplicationVersion',
 'pyComponent',
 'pyIssue',
 'pyTempDouble',
 'pyApplication',
 'pyInteraction',
 'pyName',
 'pyTemplateName',
 'pyEmailSubject',
 'pyTemplateType',
 'pyIsVolumeConstraintEnabled',
 'pyLabel',
 'pyStrategy']

In [12]:
display(df.select(pl.col("pyChannel", "pyGroup", "pyIssue")).unique())

shape: (20, 3)
┌───────────┬─────────────────────────┬─────────────┐
│ pyChannel ┆ pyGroup                 ┆ pyIssue     │
│ ---       ┆ ---                     ┆ ---         │
│ str       ┆ str                     ┆ str         │
╞═══════════╪═════════════════════════╪═════════════╡
│ Email     ┆ AwarenessandInspiration ┆ Experience  │
│ Email     ┆ Select                  ┆ Activation  │
│ Email     ┆ AppDownload             ┆ Acquisition │
│ Email     ┆ Select                  ┆ Acquisition │
│ ...       ┆ ...                     ┆ ...         │
│ null      ┆ Select                  ┆ Acquisition │
│ null      ┆ Alerts                  ┆ Sales       │
│ null      ┆ Discounts               ┆ Sales       │
│ null      ┆ AppDownload             ┆ Acquisition │
└───────────┴─────────────────────────┴─────────────┘

In [4]:
df.select(pl.col("pyTreatment")).unique()

shape: (2256, 1)
┌─────────────────────────────────────┐
│ pyTreatment                         │
│ ---                                 │
│ str                                 │
╞═════════════════════════════════════╡
│ VissenAwarenessEmailTest11_Email... │
│ Test_Baby_Toys_2_Email              │
│ Livingtestaction3_Email_1           │
│ Test_Baby_Babygym_Email             │
│ ...                                 │
│ B7D_Test_A_Web_2dagen_nl            │
│ B7D_Test_A_Web_Laatste_Kans_nl      │
│ B7D_Hardlopers_Web_nl               │
│ B7D_Hardloper_Web_fr                │
└─────────────────────────────────────┘

In [13]:
df.head()

shape: (5, 99)
┌─────┬────────────┬────────────┬───────────┬─────┬────────────┬────────────┬────────────┬────────────┐
│     ┆ IsSMSEnabl ┆ pySubjectT ┆ ProductNa ┆ ... ┆ IsPaidEnab ┆ ImageAltTe ┆ ImageURL_W ┆ ImageTarge │
│ --- ┆ ed         ┆ ype        ┆ me        ┆     ┆ led        ┆ xt_Web     ┆ eb         ┆ tURL_Web   │
│ i64 ┆ ---        ┆ ---        ┆ ---       ┆     ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│     ┆ f64        ┆ str        ┆ str       ┆     ┆ str        ┆ str        ┆ str        ┆ str        │
╞═════╪════════════╪════════════╪═══════════╪═════╪════════════╪════════════╪════════════╪════════════╡
│ 0   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 1   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 2   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 3   ┆ 0.0        ┆ Data-Decis ┆ null      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
│ 4   ┆ 0.0        ┆ Data-Decis ┆ Tuin      ┆ ... ┆ null       ┆ null       ┆ null       ┆ null       │
│     ┆            ┆ ion-Reques ┆           ┆     ┆            ┆            ┆            ┆            │
│     ┆            ┆ t-Customer ┆           ┆     ┆            ┆            ┆            ┆            │
└─────┴────────────┴────────────┴───────────┴─────┴────────────┴────────────┴────────────┴────────────┘

In [25]:
# 20221003T050000.000 GMT
query = (
    df.filter(pl.col("pyIsPropositionActive") != "Never")
    .with_columns(
        pl.col('StartDate', 'EndDate')
        .str.replace(" GMT", "")
        .str.strptime(pl.Datetime, fmt="%Y%m%dT%H%M%S%.f"),
        pl.col("pxUpdateDateTime")
        .cast(pl.Datetime).dt.with_time_unit("ms")
        .alias("pxUpdateDateTime_")
    )
    .select('StartDate', 'EndDate', 'pxUpdateDateTime_', pl.col('^py.*$'))
)
query
# StartDate
#EndDate

shape: (2049, 25)
┌─────────┬─────────┬────────────┬────────────┬─────┬────────────┬────────────┬─────────┬──────────┐
│ StartDa ┆ EndDate ┆ pxUpdateDa ┆ pySubjectT ┆ ... ┆ pyTemplate ┆ pyIsVolume ┆ pyLabel ┆ pyStrate │
│ te      ┆ ---     ┆ teTime_    ┆ ype        ┆     ┆ Type       ┆ Constraint ┆ ---     ┆ gy       │
│ ---     ┆ datetim ┆ ---        ┆ ---        ┆     ┆ ---        ┆ Enabled    ┆ str     ┆ ---      │
│ datetim ┆ e[ns]   ┆ datetime[m ┆ str        ┆     ┆ str        ┆ ---        ┆         ┆ str      │
│ e[ns]   ┆         ┆ s]         ┆            ┆     ┆            ┆ bool       ┆         ┆          │
╞═════════╪═════════╪════════════╪════════════╪═════╪════════════╪════════════╪═════════╪══════════╡
│ 2023-02 ┆ 2023-09 ┆ 2023-03-22 ┆ Data-Decis ┆ ... ┆ DB         ┆ false      ┆ Je tuin ┆ ActionTr │
│ -22 23: ┆ -29 22: ┆ 09:00:46   ┆ ion-Reques ┆     ┆            ┆            ┆ lente   ┆ eatmentM │
│ 00:00   ┆ 00:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆ klaar   ┆ etadata  │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ met hog ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ edruk.. ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ .       ┆          │
│ 2023-02 ┆ 2023-09 ┆ 2023-03-22 ┆ Data-Decis ┆ ... ┆ DB         ┆ false      ┆ Je tuin ┆ ActionTr │
│ -22 23: ┆ -29 22: ┆ 09:00:46   ┆ ion-Reques ┆     ┆            ┆            ┆ lente   ┆ eatmentM │
│ 00:00   ┆ 00:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆ klaar   ┆ etadata  │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ met hog ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ edruk.. ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ .       ┆          │
│ 2023-02 ┆ 2023-07 ┆ 2023-02-27 ┆ Data-Decis ┆ ... ┆ DB         ┆ false      ┆ Vind    ┆ ActionTr │
│ -16 23: ┆ -30 22: ┆ 16:57:44   ┆ ion-Reques ┆     ┆            ┆            ┆ hier    ┆ eatmentM │
│ 00:00   ┆ 00:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆ nieuwe  ┆ etadata  │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ Pokémon ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ release ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ ...     ┆          │
│ 2023-02 ┆ 2023-07 ┆ 2023-02-27 ┆ Data-Decis ┆ ... ┆ DB         ┆ false      ┆ Vind    ┆ ActionTr │
│ -16 23: ┆ -30 22: ┆ 16:57:44   ┆ ion-Reques ┆     ┆            ┆            ┆ hier    ┆ eatmentM │
│ 00:00   ┆ 00:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆ nieuwe  ┆ etadata  │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ Pokémon ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ release ┆          │
│         ┆         ┆            ┆            ┆     ┆            ┆            ┆ ...     ┆          │
│ ...     ┆ ...     ┆ ...        ┆ ...        ┆ ... ┆ ...        ┆ ...        ┆ ...     ┆ ...      │
│ 2023-03 ┆ 2023-04 ┆ 2023-03-23 ┆ Data-Decis ┆ ... ┆ null       ┆ false      ┆ B7D -   ┆ ActionTr │
│ -30 22: ┆ -02 21: ┆ 13:48:42   ┆ ion-Reques ┆     ┆            ┆            ┆ Test A  ┆ eatmentM │
│ 01:00   ┆ 59:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆         ┆ etadata  │
│ 2023-03 ┆ 2023-04 ┆ 2023-03-23 ┆ Data-Decis ┆ ... ┆ null       ┆ false      ┆ B7D -   ┆ ActionTr │
│ -30 22: ┆ -02 21: ┆ 13:48:42   ┆ ion-Reques ┆     ┆            ┆            ┆ Test A  ┆ eatmentM │
│ 01:00   ┆ 59:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆         ┆ etadata  │
│ 2023-03 ┆ 2023-04 ┆ 2023-03-23 ┆ Data-Decis ┆ ... ┆ null       ┆ false      ┆ B7D -   ┆ ActionTr │
│ -28 22: ┆ -02 21: ┆ 14:02:32   ┆ ion-Reques ┆     ┆            ┆            ┆ Hardlop ┆ eatmentM │
│ 01:00   ┆ 59:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆ er      ┆ etadata  │
│ 2023-03 ┆ 2023-04 ┆ 2023-03-23 ┆ Data-Decis ┆ ... ┆ null       ┆ false      ┆ B7D -   ┆ ActionTr │
│ -28 22: ┆ -02 21: ┆ 14:02:32   ┆ ion-Reques ┆     ┆            ┆            ┆ Hardlop ┆ eatmentM │
│ 01:00   ┆ 59:00   ┆            ┆ t-Customer ┆     ┆            ┆            ┆ er      ┆ etadata  │
└─────────┴─────────┴────────────┴────────────┴─────┴────────────┴────────────┴─────────┴──────────┘

In [16]:
df.select(pl.col('^.*Date.*$')).columns

['StartDate', 'pxUpdateDateTime', 'EndDate']