In [1]:
from treeanalysis import TreeAnalysis
import polars as pl

### set folder and file paths

In [2]:
folder_path = "/Users/hasss/dev/bol.com/modelSnapshots/"
model_filename = "Data-Decision-ADM-ModelSnapshot_AdmModelsSnapshot_20230308T113755_GMT/data.json"
plots_folder_path = "/Users/hasss/dev/pega-datascientist-tools/output"
tree_analysis = TreeAnalysis(
    past_n_snapshots='all', 
    compare_first_n_trees=4, 
    folder_path=folder_path,
    model_filename=model_filename,
    plots_folder_path=plots_folder_path
)

In [3]:
df = tree_analysis.get_df()

In [4]:
df.head()

shape: (5, 15)
┌─────────────┬────────────┬───────────┬──────────┬─────┬────────────┬───────────┬───────┬─────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ ... ┆ left_child ┆ right_chi ┆ depth ┆ flag    │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆     ┆ ---        ┆ ld        ┆ ---   ┆ ---     │
│ str         ┆ ---        ┆ ---       ┆ str      ┆     ┆ f64        ┆ ---       ┆ i64   ┆ str     │
│             ┆ str        ┆ str       ┆          ┆     ┆            ┆ f64       ┆       ┆         │
╞═════════════╪════════════╪═══════════╪══════════╪═════╪════════════╪═══════════╪═══════╪═════════╡
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ ... ┆ 4.0        ┆ 7.0       ┆ 3     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ ... ┆ 10.0       ┆ 13.0      ┆ 4     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ ... ┆ 20.0       ┆ 23.0      ┆ 2     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ ... ┆ 4.0        ┆ 5.0       ┆ 3     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ Mobile_Clic ┆ 20230303   ┆ 20230304  ┆ 20230303 ┆ ... ┆ 15.0       ┆ 16.0      ┆ 4     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
└─────────────┴────────────┴───────────┴──────────┴─────┴────────────┴───────────┴───────┴─────────┘

In [6]:
def run_query(query):
    with pl.Config() as cfg:
        cfg.set_fmt_str_lengths(100)
        display(query)

In [7]:
query = (
    df
    .filter(pl.col("change_type") == "split_to_prune")
    .groupby(['channel', 'change_type', 'predictor'])
    .agg(pl.count())
)
run_query(query)

shape: (24, 4)
┌───────────────────────────────┬────────────────┬─────────────────────────────────────────┬───────┐
│ channel                       ┆ change_type    ┆ predictor                               ┆ count │
│ ---                           ┆ ---            ┆ ---                                     ┆ ---   │
│ str                           ┆ str            ┆ str                                     ┆ u32   │
╞═══════════════════════════════╪════════════════╪═════════════════════════════════════════╪═══════╡
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ Customer.BehavioralData.VisitShareL1Gam ┆ 2     │
│                               ┆                ┆ es                                      ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ Customer.Is13261CategoryOrderedIn24M    ┆ 1     │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ IH.Web.Inbound.Clicked.pxLastOutcomeTim ┆ 1     │
│                               ┆                ┆ e.DaysSince                             ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ IH.Web.Inbound.Clicked.pyHistoricalOutc ┆ 1     │
│                               ┆                ┆ omeCount                                ┆       │
│ ...                           ┆ ...            ┆ ...                                     ┆ ...   │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.BehavioralData.VisitShareL1Per ┆ 2     │
│                               ┆                ┆ soonlijkeverzorging                     ┆       │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ Customer.DaysSinceLastOrder             ┆ 1     │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ IH.Web.Inbound.Impression.pxLastOutcome ┆ 1     │
│                               ┆                ┆ Time.DaysSince                          ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.BehavioralData.L1ShelfVisitMos ┆ 1     │
│                               ┆                ┆ tInSession                              ┆       │
└───────────────────────────────┴────────────────┴─────────────────────────────────────────┴───────┘

In [8]:
query = (
    df.filter(
            pl.col("channel").is_in(["Mobile_Click_Through_Rate_AGB"]) &
            pl.col("change_type").is_in(["split_to_split"]) & 
            pl.col("predictor").is_in(["pyIssue"])
        )
)
run_query(query)

shape: (2, 15)
┌─────────────┬────────────┬───────────┬──────────┬─────┬────────────┬───────────┬───────┬─────────┐
│ channel     ┆ snapshot_f ┆ snapshot_ ┆ snapshot ┆ ... ┆ left_child ┆ right_chi ┆ depth ┆ flag    │
│ ---         ┆ rom        ┆ to        ┆ ---      ┆     ┆ ---        ┆ ld        ┆ ---   ┆ ---     │
│ str         ┆ ---        ┆ ---       ┆ str      ┆     ┆ f64        ┆ ---       ┆ i64   ┆ str     │
│             ┆ str        ┆ str       ┆          ┆     ┆            ┆ f64       ┆       ┆         │
╞═════════════╪════════════╪═══════════╪══════════╪═════╪════════════╪═══════════╪═══════╪═════════╡
│ Mobile_Clic ┆ 20230307   ┆ 20230308  ┆ 20230307 ┆ ... ┆ 4.0        ┆ 5.0       ┆ 3     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ Mobile_Clic ┆ 20230306   ┆ 20230307  ┆ 20230306 ┆ ... ┆ 38.0       ┆ 49.0      ┆ 2     ┆ crimson │
│ k_Through_R ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
│ ate_AGB     ┆            ┆           ┆          ┆     ┆            ┆           ┆       ┆         │
└─────────────┴────────────┴───────────┴──────────┴─────┴────────────┴───────────┴───────┴─────────┘

In [9]:
query = (
    df
    .groupby(['channel', 'change_type', 'predictor', 'depth'])
    .agg(pl.count())
)
run_query(query)

shape: (88, 5)
┌───────────────────────────────┬────────────────┬─────────────────────────────────┬───────┬───────┐
│ channel                       ┆ change_type    ┆ predictor                       ┆ depth ┆ count │
│ ---                           ┆ ---            ┆ ---                             ┆ ---   ┆ ---   │
│ str                           ┆ str            ┆ str                             ┆ i64   ┆ u32   │
╞═══════════════════════════════╪════════════════╪═════════════════════════════════╪═══════╪═══════╡
│ Mobile_Click_Through_Rate_AGB ┆ split_to_split ┆ Customer.BehavioralData.VisitSh ┆ 4     ┆ 4     │
│                               ┆                ┆ areL1Persoonlijkeverzorging     ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_split ┆ IH.Web.Inbound.Clicked.pyHistor ┆ 3     ┆ 1     │
│                               ┆                ┆ icalOutcomeCount                ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_prune ┆ Customer.NextBestShelfL2        ┆ 5     ┆ 1     │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ Customer.NextBestShelfL2        ┆ 5     ┆ 1     │
│ ...                           ┆ ...            ┆ ...                             ┆ ...   ┆ ...   │
│ Web_Click_Through_Rate_AGB    ┆ split_to_prune ┆ Customer.BehavioralData.VisitSh ┆ 5     ┆ 1     │
│                               ┆                ┆ areL1Games                      ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_split ┆ pyIssue                         ┆ 3     ┆ 1     │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_split ┆ Customer.BehavioralData.VisitSh ┆ 3     ┆ 2     │
│                               ┆                ┆ areL1Kantoorschool              ┆       ┆       │
│ Mobile_Click_Through_Rate_AGB ┆ split_to_split ┆ IH.Web.Inbound.Clicked.pxLastGr ┆ 3     ┆ 1     │
│                               ┆                ┆ oupID                           ┆       ┆       │
└───────────────────────────────┴────────────────┴─────────────────────────────────┴───────┴───────┘